# Generated by Django 3.2.8 on 2021-10-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Faq',
            new_name='faq',
        ),
    ]
