# Generated by Django 3.2.8 on 2021-10-29 05:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_page_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cssorder',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('true', 'true')], help_text='for faq use true and for about use active', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
