# Generated by Django 3.2.8 on 2021-11-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_page_link_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link_active',
            field=models.BooleanField(default=True),
        ),
    ]
