# Generated by Django 3.2.8 on 2021-11-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_page_link_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='link_active',
        ),
    ]
