# Generated by Django 3.2.10 on 2022-01-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20220109_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_leader',
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='title ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='description', max_length=500, null=True),
        ),
    ]
