# Generated by Django 3.2.10 on 2022-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20220109_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_ogimage',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_ogimagealt',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_ogtitle',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_ogurl',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_twittercard',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_twitterimage',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_twitterimagealt',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_twittersite',
        ),
        migrations.AddField(
            model_name='page',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='linked',
            field=models.BooleanField(default=True),
        ),
    ]
