# Generated by Django 3.1.3 on 2021-10-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-contact_date',), 'verbose_name': 'Customers-message', 'verbose_name_plural': 'Customers-messages'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Contactus', 'verbose_name_plural': 'Contactus'},
        ),
        migrations.AddField(
            model_name='contact',
            name='pick_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
