# Generated by Django 3.2.7 on 2021-10-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20211001_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='large_plot_size',
            field=models.IntegerField(blank=True, help_text='only add plots larger than 10 acres', null=True),
        ),
    ]
