# Generated by Django 3.2.7 on 2021-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_rename_for_listing_for_rs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='for_rs',
            field=models.CharField(blank=True, choices=[('For rent', 'For rent'), ('For lease', 'For lease'), ('For Sale', 'For sale')], max_length=100, null=True),
        ),
    ]
