# Generated by Django 3.2.10 on 2022-01-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_auto_20220109_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='meta_leader',
        ),
        migrations.AddField(
            model_name='listing',
            name='meta_title',
            field=models.CharField(blank=True, help_text='title ', max_length=200, null=True),
        ),
    ]
