# Generated by Django 3.2.7 on 2021-10-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20211001_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='House',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Rental',
            new_name='rental',
        ),
    ]
