# Generated by Django 3.2.7 on 2021-10-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20211001_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Large_plot_size',
            new_name='large_plot_size',
        ),
        migrations.AddField(
            model_name='listing',
            name='document_type',
            field=models.CharField(choices=[('......', '......'), ('Title', 'Title'), ('Certificate', 'Certificate')], default='......', max_length=100),
        ),
    ]
