# Generated by Django 3.2.7 on 2021-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_large_plot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='large_plot_size',
            field=models.IntegerField(blank=True, default=0, help_text='only add plots larger than 10 acres', null=True),
        ),
    ]
