# Generated by Django 3.2.7 on 2021-10-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20211001_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='document_type',
            field=models.CharField(choices=[('......', '......'), ('Title', 'Title'), ('Certificate', 'Certificate'), ('Agreement', 'Agreement')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_type',
            field=models.CharField(choices=[('......', '......'), ('Mansionnete', 'Mansionnete'), ('Bungalow', 'Bungalow'), ('Apartment', 'Apartment'), ('Studio', 'Studio'), ('Alcove Studio', 'Alcove Studio'), ('Convertible Studio', 'Convertible Studio'), ('Convertible Studio', 'Convertible Studio'), ('Duplex/Triplex', 'Duplex/Triplex'), ('Junior 1 Bedroom', 'Junior 1 Bedroom'), ('Garden Apartment', 'Garden Apartment'), ('Railroad Apartment', 'Railroad Apartment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='large_plot_size',
            field=models.IntegerField(blank=True, default=0, help_text='state number of acres ..only for plots larger than 10acres', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='plot_size',
            field=models.CharField(choices=[('......', '......'), ('40X80ft', '40X80ft'), ('50X100ft', '50X100ft'), ('100X100ft', '100X100ft'), ('1 Acre', '1 Acre'), ('2 Acre', '2 Acre'), ('3 Acre', '3 Acre'), ('4 Acre', '4 Acre'), ('5 Acre', '5 Acre'), ('6 Acre', '6 Acre'), ('7 Acre', '7 Acre'), ('8 Acre', '8 Acre'), ('9 Acre', '9 Acre'), ('10 Acre', '10 Acre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='plot_type',
            field=models.CharField(choices=[('......', '......'), ('Beach', 'Beach'), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Farm', 'Farm'), ('Ranch', 'Ranch')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='soil_type',
            field=models.CharField(choices=[('......', '......'), ('Cotton Soil', 'Cotton Soil'), ('Red Soil', 'Red Soil'), ('Sand Soil', 'Sand Soil'), ('Brown soil', 'Brown Soil')], max_length=100),
        ),
    ]
