# Generated by Django 3.2.7 on 2021-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_listing_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
