# Generated by Django 3.2.7 on 2021-10-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_features_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('label',)},
        ),
    ]
