# Generated by Django 3.2.7 on 2021-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20211002_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.ManyToManyField(to='listings.Feature'),
        ),
    ]
