# Generated by Django 3.2.7 on 2021-10-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_feature_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=models.ManyToManyField(related_name='listings', to='listings.Feature'),
        ),
    ]
