# Generated by Django 3.2.7 on 2021-10-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='For',
            field=models.CharField(blank=True, choices=[('For rent', 'For rent'), ('For Sale', 'For sale')], max_length=100, null=True),
        ),
    ]
