# Generated by Django 3.2.8 on 2021-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_faq_page_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='photo',
            field=models.ImageField(blank=True, default='landscape.jpg', help_text='your image must be jpg format to save', null=True, upload_to='Pages_photos/%Y/%m/%d/'),
        ),
    ]
