# Generated by Django 3.2.8 on 2021-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_page_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='particular name of the area as known to the locals', max_length=500, null=True, unique=True),
        ),
    ]
