# Generated by Django 3.2.8 on 2021-10-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_page_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cssorder',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('True', 'True')], max_length=100, null=True),
        ),
    ]
