# Generated by Django 3.2.8 on 2021-10-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_page_cssorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created_by',
        ),
    ]
