# Generated by Django 3.2.8 on 2021-10-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20211029_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='core',
            field=models.BooleanField(default=False),
        ),
    ]
