# Generated by Django 3.2.8 on 2021-11-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_page_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_active',
            field=models.BooleanField(default=False),
        ),
    ]
