# Generated by Django 3.2.10 on 2022-01-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_page_link_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='description of the leader', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='eg python, django, web, development', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_leader',
            field=models.CharField(blank=True, help_text='name of the leader ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_ogimage',
            field=models.CharField(blank=True, help_text='https://janowski.dev/static/cover.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_ogimagealt',
            field=models.CharField(blank=True, help_text='a green cover image with django logo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_ogtitle',
            field=models.CharField(blank=True, help_text='interesting article title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_ogurl',
            field=models.CharField(blank=True, help_text='add a link to the leader like this https://janowski.dev/leader/2020/04/05/mpmwangi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_twittercard',
            field=models.CharField(blank=True, help_text='summary_large_image', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_twitterimage',
            field=models.CharField(blank=True, help_text='https/example.com/image.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_twitterimagealt',
            field=models.CharField(blank=True, help_text='description of image', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_twittersite',
            field=models.CharField(blank=True, help_text='@MaciejJanowski', max_length=300, null=True),
        ),
    ]
