# Generated by Django 3.1.3 on 2021-10-04 03:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_auto_20211004_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
