# Generated by Django 3.2.7 on 2021-10-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0014_auto_20211008_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
