# Generated by Django 3.2.8 on 2021-10-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0017_realtor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='facebook',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='realtor',
            name='twitter',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
