# Generated by Django 3.1.3 on 2021-10-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0009_remove_realtor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
