# Generated by Django 3.1.3 on 2021-10-04 04:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0010_auto_20211004_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='richtesting',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
