# Generated by Django 3.2.7 on 2021-10-05 09:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0012_alter_realtor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='richtesting',
        ),
        migrations.AlterField(
            model_name='realtor',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
