# Generated by Django 3.2.7 on 2021-10-08 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtors', '0013_auto_20211005_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='name',
        ),
        migrations.AddField(
            model_name='realtor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
