# Generated by Django 3.2.8 on 2021-10-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0018_auto_20211028_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
