# Generated by Django 3.2.7 on 2021-10-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_listing_for_rs'),
        ('adverts', '0002_remove_advert_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
