# Generated by Django 3.2.7 on 2021-10-08 13:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_advert_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='embed',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
