# Generated by Django 3.2.10 on 2022-01-08 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20211005_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
